### ISSUE TITLE
Peer to peer code review.

### ISSUE THREAD

**Issue by afizsavage** [abdessalem1998/Javascript-capstone#29]
Well done @rdnrn and @abdessalem1998.

Your project is just great. I really like the UI and the color scheme you used. 
It's just perfect.

**Comment by BonkeGcobo** [comment]
Well done @rdnrn  and @abdessalem1998 , the UI is looks good.
Your readme file is well written.

Keep Up the good work

**Comment by rdnrn** [comment]
Thank you!
